services:
  db:
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      HOST: "db"
      POSTGRES_USER: ${ADMIN}
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: ${ADMIN_DBNAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${ADMIN}"]
      interval: 5s
      timeout: 3s
      retries: 5
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - "./datasets:/app/datasets"
      - "./reports:/app/reports"
volumes:
  db_data:
  app_data: